<?php

/**
 * Implements hook_menu().
 */
function baumspenden_menu()
{
    $items['baumspende'] = [
        'title' => 'Baumspende',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['baumspenden_donation'],
        'access arguments' => ['access baumspenden donation form'],
    ];

    return $items;
}

/**
 * Builds the "baumspenden_donation" form.
 *
 * @param $form
 * @param $form_state
 *
 * @return mixed
 */
function baumspenden_donation($form, &$form_state)
{
    $form['donations'] = [
        '#type' => 'fieldset',
        '#title' => 'Baumspenden',
        '#tree' => true,
        '#prefix' => '<div id="baumspenden-donations">',
        '#suffix' => '</div>',
    ];
    if (empty($form_state['storage']['donations'])) {
        $form_state['storage']['donations'][] = [];
    }
    foreach ($form_state['storage']['donations'] as $key => $donation) {
        if (is_numeric($key)) {
            $form['donations'][$key] = [
                '#type' => 'fieldset',
            ];
            $form['donations'][$key]['amount'] = [
                '#type' => 'textfield',
                '#title' => 'Ich spende',
                '#description' => 'Für mehr als 100 Bäume und Unternehmensspenden kontaktieren Sie uns bitte unter <a href="mailto:baumspende@bergwaldprojekt.de">baumspende@bergwaldprojekt.de</a>',
                '#field_suffix' => 'Baum/Bäume',
                '#required' => true,
                '#element_validate' => [
                    'element_validate_integer_positive',
                ],
            ];
            $form['donations'][$key]['plant_info'] = [
                '#prefix' => '<div id="baumspenden-plant-info--' . $key . '">',
                '#suffix' => '</div>',
            ];
            $form['donations'][$key]['plant_info']['plant_period'] = [
                '#type' => 'select',
                '#title' => 'Pflanzperiode',
                '#options' => DrupalBaumspendenConfig::getPlantPeriods(),
                '#empty_option' => '- Auswählen -',
                '#required' => true,
                '#ajax' => [
                    'wrapper' => 'baumspenden-plant-info--' . $key,
                    'callback' => '_baumspenden_donation_plant_info',
                ],
            ];

            // Save values in the storage for later use.
            if (isset($form_state['values']['donations'][$key]['plant_info']['plant_period'])) {
                $form_state['storage']['donations'][$key]['plant_info']['plant_period'] = $form_state['values']['donations'][$key]['plant_info']['plant_period'];
            }
            if (isset($form_state['storage']['donations'][$key]['plant_info']['plant_period'])) {
                $form['donations'][$key]['plant_info']['plant_region'] = [
                    '#type' => 'select',
                    '#title' => 'Region',
                    '#options' => DrupalBaumspendenConfig::getPlantRegions(
                        $form_state['storage']['donations'][$key]['plant_info']['plant_period']
                    ),
                    '#required' => true,
                    '#ajax' => [
                        'wrapper' => 'baumspenden-plant-info--' . $key,
                        'callback' => '_baumspenden_donation_plant_info',
                    ],
                ];
            }

            // Save values in the storage for later use.
            if (isset($form_state['values']['donations'][$key]['plant_info']['plant_region'])) {
                $form_state['storage']['donations'][$key]['plant_info']['plant_region'] = $form_state['values']['donations'][$key]['plant_info']['plant_region'];
            }
            if (isset($form_state['storage']['donations'][$key]['plant_info']['plant_region'])) {
                $form['donations'][$key]['plant_info']['plant_tree'] = [
                    '#type' => 'select',
                    '#title' => 'Baumart',
                    '#options' => DrupalBaumspendenConfig::getTreeSpecies(
                        $form_state['storage']['donations'][$key]['plant_info']['plant_period']
                    ),
                    '#required' => true,
                ];
            }
            $form['donations'][$key]['plant_info']['update'] = [
                '#type' => 'submit',
                '#baumspenden_op' => 'update_plant_info',
                '#value' => t('Update'),
                '#attributes' => [
                    'class' => [
                        'hide-js',
                    ],
                ],
                '#attached' => [
                    'css' => [
                        drupal_get_path(
                            'module',
                            'baumspenden'
                        ) . '/css/baumspende.css',
                    ],
                ],
                // Only validate related fields.
                '#limit_validation_errors' => [
                    ['donations', $key, 'plant_info', 'plant_period'],
                    ['donations', $key, 'plant_info', 'plant_region'],
                ],
                // #submit is required when using #limit_validation_errors.
                '#submit' => [
                    'baumspenden_donation_submit',
                ],
                '#baumspenden_donation_key' => $key,
            ];

            if ($key != 0) {
                $form['donations'][$key]['remove'] = [
                    '#type' => 'submit',
                    '#baumspenden_op' => 'remove_donation',
                    '#value' => t('Remove'),
                    // Do not validate anything.
                    '#limit_validation_errors' => [],
                    // #submit is required when using #limit_validation_errors.
                    '#submit' => [
                        'baumspenden_donation_submit',
                    ],
                    '#ajax' => [
                        'wrapper' => 'baumspenden-donations',
                        'callback' => '_baumspenden_donation_donations',
                    ],
                    '#baumspenden_donation_key' => $key,
                ];
            }
        }
    }
    $form['donations']['add'] = [
        '#type' => 'submit',
        '#baumspenden_op' => 'add_donation',
        '#value' => 'Baumspende hinzufügen',
        // Only validate related fields.
        '#limit_validation_errors' => [],
        // #submit is required when using #limit_validation_errors.
        '#submit' => [
            'baumspenden_donation_submit',
        ],
        '#ajax' => [
            'wrapper' => 'baumspenden-donations',
            'callback' => '_baumspenden_donation_donations',
        ],
    ];

    $form['contact'] = [
        '#type' => 'fieldset',
        '#title' => 'Meine Kontaktdaten',
    ];
    $form['contact']['first_name'] = [
        '#type' => 'textfield',
        '#title' => 'Vorname',
        '#required' => true,
    ];
    $form['contact']['last_name'] = [
        '#type' => 'textfield',
        '#title' => 'Nachname',
        '#required' => true,
    ];
    $form['contact']['street_address'] = [
        '#type' => 'textfield',
        '#title' => 'Straße, Hausnummer',
        '#required' => true,
    ];
    $form['contact']['postal_code'] = [
        '#type' => 'textfield',
        '#title' => 'Postleitzahl',
        '#required' => true,
    ];
    $form['contact']['city'] = [
        '#type' => 'textfield',
        '#title' => 'Ort',
        '#required' => true,
    ];
    $form['contact']['email'] = [
        '#type' => 'textfield',
        '#title' => 'E-Mail-Adresse',
        '#required' => true,
    ];

    $form['shipping_mode'] = [
        '#type' => 'select',
        '#title' => 'Versandoption',
        '#options' => [
            'email' => 'als PDF per E-Mail',
            'postal' => 'postalisch',
            'none' => 'kein Zertifikat',
        ],
    ];

    $form['certificate_name'] = [
        '#type' => 'textfield',
        '#title' => 'Name auf Zertifikat',
        '#description' => 'max. 40 Zeichen',
        '#attributes' => [
            'placeholder' => 'Waldmariechen',
        ],
        '#maxlength' => 40,
    ];

    $form['newsletter'] = [
        '#type' => 'checkbox',
        '#title' => 'Newsletter abonnieren',
        '#description' => 'Newsletter mit aktuellen Themen rund um das Bergwaldprojekt',
    ];

    $form['gdpr_consent'] = [
        '#type' => 'checkbox',
        '#title' => 'Datenschutz',
        '#description' => 'Ich habe die <a href="' . variable_get(
                'baumspenden_gdpr_link',
                '/datenschutz'
            ) . '" target="_blank">Datenschutzerklärung</a> gelesen und akzeptiere diese.',
        '#required' => true,
    ];

    $form['actions'] = [
        '#type' => 'actions',
    ];
    $form['actions']['submit'] = [
        '#type' => 'submit',
        '#baumspenden_op' => 'preview',
        '#value' => 'Vorschau',
    ];

    return $form;
}

/**
 * Validates form submissions for the "baumspenden_donation" form.
 *
 * @param $form
 * @param $form_state
 */
function baumspenden_donation_validate($form, &$form_state)
{
    // Require a valid e-mail address.
    if (!valid_email_address($form_state['values']['email'])) {
        form_set_error(
            'email',
            'Bitte geben Sie eine gültige E-Mail-Adresse ein.'
        );
    }
}

/**
 * Processes form submissions for the "baumspenden_donation" form.
 *
 * @param $form
 * @param $form_state
 */
function baumspenden_donation_submit($form, &$form_state)
{
    // Depend on which element trigered the submission.
    switch ($form_state['triggering_element']['#baumspenden_op']) {
        case 'preview':
            // Preview (next step)
            $form_state['storage'] = $form_state['values'];
            // TODO: Process form.
            break;
        case 'update_plant_info':
            // Updating plant info fields. Simply rebuild the form.
            $form_state['rebuild'] = true;
            break;
        case 'add_donation':
            // Add values for another donation fieldset and rebuild the form.
            $form_state['storage']['donations'][] = [];
            $form_state['rebuild'] = true;
            break;
        case 'remove_donation':
            // Remove the donation fieldset values and rebuild the form.
            $key = $form_state['triggering_element']['#baumspenden_donation_key'];
            unset($form_state['storage']['donations'][$key]);
            $form_state['rebuild'] = true;
            break;
    }
}

/**
 * Returns plant info elements of the "baumspenden_donation" form to be replaced
 * by an Ajax request.
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function _baumspenden_donation_plant_info($form, &$form_state)
{
    $triggering_element_parents = $form_state['triggering_element']['#array_parents'];
    $plant_info_parents = array_slice($triggering_element_parents, 0, 3);
    return drupal_array_get_nested_value($form, $plant_info_parents);
}

/**
 * Returns donations elements of the "baumspenden_donation" form to be replaced
 * by an Ajax request.
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function _baumspenden_donation_donations($form, &$form_state)
{
    return $form['donations'];
}
