<?php
/*-------------------------------------------------------+
| Bergwaldprojekt Baumspenden                            |
| Copyright (C) 2010 SYSTOPIA                            |
+--------------------------------------------------------+
| This program is released as free software under the    |
| Affero GPL license. You can redistribute it and/or     |
| modify it under the terms of this license which you    |
| can read by viewing the included agpl.txt or online    |
| at www.gnu.org/licenses/agpl.html. Removal of this     |
| copyright header is strictly prohibited without        |
| written permission from the original author(s).        |
+--------------------------------------------------------*/

/**
 * Implements hook_menu().
 */
function baumspenden_menu()
{
    $items['baumspende'] = [
        'title' => 'Baumspende',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['baumspenden_donation'],
        'access arguments' => ['access baumspenden donation form'],
    ];

    return $items;
}

/**
 * Implements hook_permission().
 */
function baumspenden_permission()
{
    $permissions = [];

    $permissions['access baumspenden donation form'] = [
        'title' => t('Acces Baumspenden donation form'),
        'description' => t('Views and submit Baumspenden donation form'),
    ];

    return $permissions;
}

/**
 * Implements hook_forms().
 */
function baumspenden_forms($form_id, $args)
{
    $forms['baumspenden_donation'] = array(
        // This will call: DrupalBaumspendenDonationForm::build().
        'callback' => array(
            'DrupalBaumspendenDonationForm',
            'build',
        ),
        // The base_form_id is required when the callback is a static function in
        // a class. This can also be used to keep newer code backwards compatible.
        'base_form_id' => 'baumspenden_donation',
    );
    return $forms;
}

/**
 * Implements hook_commerce_product_type_info().
 */
function baumspenden_commerce_product_type_info()
{
    $product_types = [];

    // Add a product type for Baumspende donations.
    $product_types[DrupalBaumspendenDonation::PRODUCT_TYPE] = [
        'type' => DrupalBaumspendenDonation::PRODUCT_TYPE,
        'name' => 'Baumspende',
        'description' => 'Baumspende',
    ];

    return $product_types;
}

/**
 * Implements hook_commerce_cart_product_add().
 */
function baumspenden_commerce_cart_product_add($order, $product, $quantity, $line_item) {
  if ($product->type != DrupalBaumspendenDonation::PRODUCT_TYPE) {
    $order_altered = FALSE;
    foreach (
      entity_metadata_wrapper(
        'commerce_order',
        $order
      )->commerce_line_items as $delta => $order_line_item_wrapper
    ) {
      $order_product = commerce_product_load($order_line_item_wrapper->commerce_product->raw());
      if ($order_product->type == DrupalBaumspendenDonation::PRODUCT_TYPE) {
        commerce_cart_order_product_line_item_delete(
          $order,
          $order_line_item_wrapper->line_item_id->raw(),
          TRUE
        );
        $order_altered = TRUE;
      }
    }
    if ($order_altered) {
      commerce_order_save($order);
    }
  }
}
