<?php
/*-------------------------------------------------------+
| Bergwaldprojekt Baumspenden                            |
| Copyright (C) 2010 SYSTOPIA                            |
+--------------------------------------------------------+
| This program is released as free software under the    |
| Affero GPL license. You can redistribute it and/or     |
| modify it under the terms of this license which you    |
| can read by viewing the included agpl.txt or online    |
| at www.gnu.org/licenses/agpl.html. Removal of this     |
| copyright header is strictly prohibited without        |
| written permission from the original author(s).        |
+--------------------------------------------------------*/

/**
 * Implements hook_menu().
 */
function baumspenden_menu()
{
    $items['baumspende'] = [
        'title' => 'Baumspende',
        'page callback' => 'drupal_get_form',
        'page arguments' => ['baumspenden_donation'],
        'access arguments' => ['access baumspenden donation form'],
    ];

    return $items;
}

/**
 * Implements hook_permission().
 */
function baumspenden_permission()
{
    $permissions = [];

    $permissions['access baumspenden donation form'] = [
        'title' => t('Acces Baumspenden donation form'),
        'description' => t('Views and submit Baumspenden donation form'),
    ];

    return $permissions;
}

/**
 * Builds the "baumspenden_donation" form.
 *
 * @param $form
 * @param $form_state
 *
 * @return mixed
 */
function baumspenden_donation($form, &$form_state)
{
    return DrupalBaumspendenDonationForm::build($form, $form_state);
}

/**
 * Validates form submissions for the "baumspenden_donation" form.
 *
 * @param $form
 * @param $form_state
 */
function baumspenden_donation_validate($form, &$form_state)
{
    DrupalBaumspendenDonationForm::validate($form, $form_state);
}

/**
 * Processes form submissions for the "baumspenden_donation" form.
 *
 * @param $form
 * @param $form_state
 */
function baumspenden_donation_submit($form, &$form_state)
{
    DrupalBaumspendenDonationForm::submit($form, $form_state);
}

/**
 * Implements hook_commerce_product_type_info().
 */
function baumspenden_commerce_product_type_info()
{
    $product_types = [];

    // Add a product type for Baumspende donations.
    $product_types['baumspende'] = [
        'type' => 'baumspende',
        'name' => 'Baumspende',
        'description' => 'Baumspende',
    ];

    return $product_types;
}
